apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: clusters-global
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
        - cluster: ds-nonprod
          url: https://240C6FDEC9ED98AEF06D25AE899DFAAD.gr7.us-east-1.eks.amazonaws.com
          values:
            project: ds-nonprod
            repoURL: https://gitlab.com/yumbrands/yc-data-adv-analytics/operations.git
            path: '_global/gitops/nonprod/'
            branch: 'master'
        - cluster: ds-prod
          url: https://240C6FDEC9ED98AEF06D25AE899DFAAD.gr7.us-east-1.eks.amazonaws.com
          values:
            project: ds-prod
            repoURL: https://gitlab.com/yumbrands/yc-data-adv-analytics/operations.git
            path: '_global/gitops/prod/'
            branch: 'master'
  template:
    metadata:
      name: '{{.cluster}}-gitops'
    spec:
      project: '{{.values.project}}'
      source:
        repoURL: '{{.values.repoURL}}'
        targetRevision: '{{.values.branch}}'
        path: '{{.values.path}}'
      destination:
        name: '{{.cluster}}'
        namespace: 'argocd'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true