apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-specifics
  namespace: argocd
spec:
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://gitlab.com/yumbrands/yumdev/yumsre-infraops/operations-infra.git
      revision: main
      directories:
      - path: shared-services/helm/shared-services-tools/helm/argocd/clusters/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: argocd
      source:
        repoURL: https://gitlab.com/yumbrands/yumdev/yumsre-infraops/operations-infra.git
        targetRevision: main
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
